name: Create Release with Android APK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Android App
        run: ionic capacitor build android --prod --no-open

      - name: Generate Android APK
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Rename file
        run: mv ./android/app/build/outputs/apk/debug/app-debug.apk ./android/app/build/outputs/apk/eportfolio-cicd_${{ env.RELEASE_VERSION }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./changelogs/${{ env.RELEASE_VERSION }}-changelog.md
          prerelease: true
          files: ./android/app/build/outputs/apk/eportfolio-cicd_${{ env.RELEASE_VERSION }}.apk
