# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

#name: Build and deploy container app to Azure Web App - e-portfolio-cicd
#
#on:
#  push:
#    branches:
#      - feature/azure-pipeline
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: 'ubuntu-latest'
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#
#    - name: Log in to registry
#      uses: docker/login-action@v1
#      with:
#        registry: https://ghcr.io/
#        username: ${{ secrets.AzureAppService_ContainerUsername_59f8de182e174e01ae627099954ae623 }}
#        password: ${{ secrets.AzureAppService_ContainerPassword_95549dae4096467193278aebfcf48c11 }}
#
#    - name: Build and push container image to registry
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_59f8de182e174e01ae627099954ae623 }}/e-portfolio-cicd:${{ github.sha }}
#        file: ./Dockerfile
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#    - name: Deploy to Azure Web App
#      id: deploy-to-webapp
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'e-portfolio-cicd'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2446b4bcefb54f28af9557dd3db07e2c }}
#        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_59f8de182e174e01ae627099954ae623 }}/e-portfolio-cicd:${{ github.sha }}'
